=== dmorcellet/delta-leo/src/main/java/delta/leo/model/io/xml/Model.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!-- Main object : Model -->
<!ELEMENT MODEL (BINARY_ASSOCIATION|COMPOSITION|ENTITY)*>
<!ATTLIST MODEL
	NAME NMTOKEN #IMPLIED
>

<!-- Entity -->
<!ELEMENT ENTITY (FIELD|COMPOUND_FIELD)*>
<!ATTLIST ENTITY
	NAME NMTOKEN #REQUIRED
	SUPER NMTOKEN #IMPLIED
>

<!-- Field properties -->
<!ELEMENT PROPERTIES EMPTY>
<!ATTLIST PROPERTIES
	ID NMTOKEN #IMPLIED
	MANDATORY NMTOKEN #IMPLIED
	NAME NMTOKEN #IMPLIED
>

<!-- Field -->
<!ELEMENT FIELD (PROPERTIES,TYPE)>
<!ATTLIST FIELD
	NAME NMTOKEN #REQUIRED
>

<!-- Type description -->
<!ELEMENT TYPE (PARAM)*>
<!ATTLIST TYPE
	CLASS NMTOKEN #REQUIRED
>

<!-- Type description -->
<!ELEMENT PARAM EMPTY>
<!ATTLIST PARAM
	NAME NMTOKEN #REQUIRED
	VALUE CDATA #REQUIRED
>

<!-- Compound field -->
<!ELEMENT COMPOUND_FIELD (PROPERTIES,FIELDS)>
<!ATTLIST COMPOUND_FIELD NAME NMTOKEN #REQUIRED>
<!ELEMENT FIELDS (FIELD)*>

<!-- Binary association -->
<!ELEMENT BINARY_ASSOCIATION (A,B,AtoB,BtoA)>
<!ATTLIST BINARY_ASSOCIATION NAME CDATA #REQUIRED>

<!ELEMENT A EMPTY>
<!ATTLIST A
	ENTITY_NAME NMTOKEN #REQUIRED
	ROLE CDATA #REQUIRED
>
<!ELEMENT B EMPTY>
<!ATTLIST B
	ENTITY_NAME NMTOKEN #REQUIRED
	ROLE CDATA #REQUIRED
>
<!ELEMENT AtoB EMPTY>
<!ATTLIST AtoB
	MAX NMTOKEN #REQUIRED
	MEANING CDATA #REQUIRED
	MIN NMTOKEN #REQUIRED
	ORDERED NMTOKEN #IMPLIED
	TRAVERSABLE NMTOKEN #IMPLIED
>
<!ELEMENT BtoA EMPTY>
<!ATTLIST BtoA
	MAX NMTOKEN #REQUIRED
	MEANING CDATA #REQUIRED
	MIN NMTOKEN #REQUIRED
	ORDERED NMTOKEN #REQUIRED
	TRAVERSABLE NMTOKEN #IMPLIED
>

<!-- Composition -->
<!ELEMENT COMPOSITION EMPTY>
<!ATTLIST COMPOSITION
	NAME CDATA #REQUIRED
	MIN NMTOKEN #REQUIRED
	MAX NMTOKEN #REQUIRED
	SOURCE NMTOKEN #REQUIRED
	TARGET NMTOKEN #REQUIRED
>

=== dmorcellet/delta-leo/src/test/java/delta/leo/examples/test/TestModel.xml
<?xml version="1.0"?>
<!--<!DOCTYPE MODEL SYSTEM 'delta/leo/model/Model.dtd'> -->
<MODEL>
	<ENTITY NAME="B" SUPER="A">
		<FIELD NAME="INDEX">
			<PROPERTIES MANDATORY="true" ID="true" NAME="false"/>
			<TYPE CLASS="INTEGER">
				<PARAM NAME="MIN" VALUE="1" />
				<PARAM NAME="MAX" VALUE="5" />
			</TYPE>
		</FIELD>
		<FIELD NAME="NAME">
			<PROPERTIES MANDATORY="true" ID="true" NAME="false"/>
			<TYPE CLASS="STRING">
				<PARAM NAME="MIN_LENGTH" VALUE="3" />
				<PARAM NAME="MAX_LENGTH" VALUE="10" />
				<PARAM NAME="MULTILINES" VALUE="true" />
			</TYPE>
		</FIELD>
		<FIELD NAME="OPTIONS">
			<PROPERTIES MANDATORY="true" ID="true" NAME="false"/>
			<TYPE CLASS="CHOICE">
				<PARAM NAME="MULTIPLE" VALUE="true" />
				<PARAM NAME="OPTION" VALUE="OPTION1|1" />
				<PARAM NAME="OPTION" VALUE="OPTION2|2" />
				<PARAM NAME="OPTION" VALUE="OPTION3|3" />
			</TYPE>
		</FIELD>
		<FIELD NAME="BIRTHDATE">
			<PROPERTIES MANDATORY="true" ID="true" NAME="false"/>
			<TYPE CLASS="DATE" />
		</FIELD>
	</ENTITY>
	<ENTITY NAME="A">
		<FIELD NAME="NAME">
			<PROPERTIES MANDATORY="true" ID="true" NAME="false"/>
			<TYPE CLASS="STRING">
				<PARAM NAME="MIN_LENGTH" VALUE="3" />
				<PARAM NAME="MAX_LENGTH" VALUE="10" />
				<PARAM NAME="MULTILINES" VALUE="true" />
			</TYPE>
		</FIELD>
		<COMPOUND_FIELD NAME="MY_COMPOUND">
			<PROPERTIES MANDATORY="true" ID="true" NAME="false"/>
			<FIELDS>
				<FIELD NAME="INDEX">
					<PROPERTIES MANDATORY="true" ID="true" NAME="false"/>
					<TYPE CLASS="INTEGER">
						<PARAM NAME="MIN" VALUE="1" />
						<PARAM NAME="MAX" VALUE="5" />
					</TYPE>
				</FIELD>
				<FIELD NAME="NAME">
					<PROPERTIES MANDATORY="true" ID="true" NAME="false"/>
					<TYPE CLASS="STRING">
						<PARAM NAME="MIN_LENGTH" VALUE="3" />
						<PARAM NAME="MAX_LENGTH" VALUE="10" />
						<PARAM NAME="MULTILINES" VALUE="false" />
					</TYPE>
				</FIELD>
			</FIELDS>
		</COMPOUND_FIELD>
	</ENTITY>
	<BINARY_ASSOCIATION NAME="A AND B">
		<A ENTITY_NAME="A" ROLE="A_ROLE"/>
		<B ENTITY_NAME="B" ROLE="B_ROLE"/>
		<AtoB MIN="0" MAX="INFINITY" ORDERED="true" TRAVERSABLE="true" MEANING="A TO B"/>
		<BtoA MIN="1" MAX="3" ORDERED="false" TRAVERSABLE="false" MEANING="B TO A"/>
	</BINARY_ASSOCIATION>
	<COMPOSITION NAME="A INCLUDES B" SOURCE="A" MIN="1" MAX="5" TARGET="B" />
</MODEL>

=== dmorcellet/delta-leo/src/test/java/delta/leo/examples/genea/model.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE MODEL SYSTEM 'delta/leo/model/io/xml/Model.dtd'>
<MODEL NAME="GENEA">
	<ENTITY NAME="PERSONNE">
		<FIELD NAME="NOM">
			<PROPERTIES MANDATORY="false" ID="false" NAME="true"/>
			<TYPE CLASS="STRING">
				<PARAM NAME="MIN_LENGTH" VALUE="0" />
				<PARAM NAME="MAX_LENGTH" VALUE="32" />
				<PARAM NAME="MULTILINES" VALUE="false" />
			</TYPE>
		</FIELD>
		<FIELD NAME="PRENOMS">
			<PROPERTIES MANDATORY="false" ID="false" NAME="true"/>
			<TYPE CLASS="STRING">
				<PARAM NAME="MIN_LENGTH" VALUE="0" />
				<PARAM NAME="MAX_LENGTH" VALUE="64" />
				<PARAM NAME="MULTILINES" VALUE="false" />
			</TYPE>
		</FIELD>
		<FIELD NAME="SIGNATURE">
			<PROPERTIES MANDATORY="false" ID="false" NAME="false"/>
			<TYPE CLASS="STRING">
				<PARAM NAME="MIN_LENGTH" VALUE="1" />
				<PARAM NAME="MAX_LENGTH" VALUE="1" />
				<PARAM NAME="MULTILINES" VALUE="false" />
			</TYPE>
		</FIELD>
		<FIELD NAME="NAISSANCE">
			<PROPERTIES MANDATORY="false" ID="false" NAME="false"/>
			<TYPE CLASS="DATE" />
		</FIELD>
		<FIELD NAME="INFOS_NAISSANCE">
			<PROPERTIES MANDATORY="false" ID="false" NAME="false"/>
			<TYPE CLASS="STRING">
				<PARAM NAME="MIN_LENGTH" VALUE="0" />
				<PARAM NAME="MAX_LENGTH" VALUE="1000" />
				<PARAM NAME="MULTILINES" VALUE="true" />
			</TYPE>
		</FIELD>
		<FIELD NAME="DECES">
			<PROPERTIES MANDATORY="false" ID="false" NAME="false"/>
			<TYPE CLASS="DATE" />
		</FIELD>
		<FIELD NAME="INFOS_DECES">
			<PROPERTIES MANDATORY="false" ID="false" NAME="false"/>
			<TYPE CLASS="STRING">
				<PARAM NAME="MIN_LENGTH" VALUE="0" />
				<PARAM NAME="MAX_LENGTH" VALUE="1000" />
				<PARAM NAME="MULTILINES" VALUE="true" />
			</TYPE>
		</FIELD>
		<FIELD NAME="COMMENTAIRE">
			<PROPERTIES MANDATORY="false" ID="false" NAME="false"/>
			<TYPE CLASS="STRING">
				<PARAM NAME="MIN_LENGTH" VALUE="0" />
				<PARAM NAME="MAX_LENGTH" VALUE="1000" />
				<PARAM NAME="MULTILINES" VALUE="true" />
			</TYPE>
		</FIELD>
	</ENTITY>
	<ENTITY NAME="ACTE">
	</ENTITY>
	<ENTITY NAME="LIEU">
	</ENTITY>
	<ENTITY NAME="PREUVE">
	</ENTITY>
	<ENTITY NAME="RECHERCHE">
	</ENTITY>
	<ENTITY NAME="COUSINAGE">
	</ENTITY>
	<ENTITY NAME="COUSIN">
	</ENTITY>
	<BINARY_ASSOCIATION NAME="LIEUX">
		<A ENTITY_NAME="LIEU" ROLE="LIEU_ENGLOBE"/>
		<B ENTITY_NAME="LIEU" ROLE="LIEU_ENGLOBANT"/>
		<AtoB MIN="0" MAX="1" TRAVERSABLE="true" MEANING="LIEU_PARENT"/>
		<BtoA MIN="0" MAX="INFINITY" ORDERED="false" TRAVERSABLE="false" MEANING=""/>
	</BINARY_ASSOCIATION>
	<BINARY_ASSOCIATION NAME="ENFANT/PERE">
		<A ENTITY_NAME="PERSONNE" ROLE="ENFANT"/>
		<B ENTITY_NAME="PERSONNE" ROLE="PERE"/>
		<AtoB MIN="0" MAX="1" TRAVERSABLE="true" MEANING="EST ENFANT DE"/>
		<BtoA MIN="0" MAX="INFINITY" ORDERED="true" TRAVERSABLE="false" MEANING="EST LE PERE DE"/>
	</BINARY_ASSOCIATION>
	<BINARY_ASSOCIATION NAME="ENFANT/MERE">
		<A ENTITY_NAME="PERSONNE" ROLE="ENFANT"/>
		<B ENTITY_NAME="PERSONNE" ROLE="MERE"/>
		<AtoB MIN="0" MAX="1" TRAVERSABLE="true" MEANING="EST ENFANT DE"/>
		<BtoA MIN="0" MAX="INFINITY" ORDERED="true" TRAVERSABLE="false" MEANING="EST LA MERE DE"/>
	</BINARY_ASSOCIATION>
	<BINARY_ASSOCIATION NAME="ENFANT/PARRAIN">
		<A ENTITY_NAME="PERSONNE" ROLE="ENFANT"/>
		<B ENTITY_NAME="PERSONNE" ROLE="PARRAIN"/>
		<AtoB MIN="0" MAX="1" TRAVERSABLE="true" MEANING="PARRAIN"/>
		<BtoA MIN="0" MAX="INFINITY" ORDERED="true" TRAVERSABLE="false" MEANING="EST LE PARRAIN DE"/>
	</BINARY_ASSOCIATION>
	<BINARY_ASSOCIATION NAME="ENFANT/MARRAINE">
		<A ENTITY_NAME="PERSONNE" ROLE="ENFANT"/>
		<B ENTITY_NAME="PERSONNE" ROLE="MARRAINE"/>
		<AtoB MIN="0" MAX="1" TRAVERSABLE="true" MEANING="MARRAINE"/>
		<BtoA MIN="0" MAX="INFINITY" ORDERED="true" TRAVERSABLE="false" MEANING="EST LA MARRAINE DE"/>
	</BINARY_ASSOCIATION>
	<BINARY_ASSOCIATION NAME="LIEU_NAISSANCE">
		<A ENTITY_NAME="PERSONNE" ROLE="BEBE"/>
		<B ENTITY_NAME="LIEU" ROLE="LIEU_NAISSANCE"/>
		<AtoB MIN="0" MAX="1" TRAVERSABLE="true" MEANING="LIEU_NAISSANCE"/>
		<BtoA MIN="0" MAX="INFINITY" ORDERED="false" TRAVERSABLE="false" MEANING="PERSONNES_NEES"/>
	</BINARY_ASSOCIATION>
	<BINARY_ASSOCIATION NAME="LIEU_DECES">
		<A ENTITY_NAME="PERSONNE" ROLE="DECEDE"/>
		<B ENTITY_NAME="LIEU" ROLE="LIEU_DECES"/>
		<AtoB MIN="0" MAX="1" TRAVERSABLE="true" MEANING="LIEU_DECES"/>
		<BtoA MIN="0" MAX="INFINITY" ORDERED="false" TRAVERSABLE="false" MEANING="PERSONNES_DECEDEES"/>
	</BINARY_ASSOCIATION>
</MODEL>

=== dmorcellet/delta-leo/src/test/java/delta/leo/examples/movies/MoviesModel.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--<!DOCTYPE MODEL SYSTEM 'delta/leo/model/Model.dtd'>-->
<MODEL NAME="HOLLYWOOD">
	<ENTITY NAME="MOVIE">
	</ENTITY>
	<ENTITY NAME="PERSON">
	</ENTITY>
	<BINARY_ASSOCIATION NAME="ACTOR/MOVIE">
		<A ENTITY_NAME="PERSON" ROLE="ACTOR"/>
		<B ENTITY_NAME="MOVIE" ROLE="MOVIE"/>
		<AtoB MIN="0" MAX="INFINITY" ORDERED="true" TRAVERSABLE="true" MEANING="PLAYS IN"/>
		<BtoA MIN="0" MAX="INFINITY" ORDERED="false" TRAVERSABLE="true" MEANING="CASTING"/>
	</BINARY_ASSOCIATION>
</MODEL>
